language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - g++-5
    - clang-3.6
    - valgrind
    - libcppunit-dev
 before_install:
 - export CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz"
 - export CMAKE_STRIP_COMPONENTS=1
 - cd /tmp
 - wget --no-check-certificate "${CMAKE_URL}" --output-document=cmake.tar.gz
 - mkdir cmake
 - tar xzf cmake.tar.gz --strip-components="${CMAKE_STRIP_COMPONENTS}" --directory cmake
 - export PATH=/tmp/cmake/bin:$PATH
 - cd -
before_script: mkdir build && cd build && if [ "${CXX}" = "clang++" ]; then export CXX=/usr/bin/clang++-3.6; fi && if [ "${CXX}" = "g++" ]; then export CXX=/usr/bin/g++-5; fi
script: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUTIL_BUILD_EXAMPLES=ON -DUTIL_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic" .. && make && ctest --verbose -D ExperimentalTest
